# 生产环境配置
server:
  port: 4001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruobing_codebook?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: user_ruobing_codebook
    password: Pjkluio0404.
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 生产环境关闭SQL日志
mybatis-plus:
  configuration:
    log-impl:

logging:
  level:
    com.ruobing.codebook: info
    root: warn
